_wandb:
    value:
        cli_version: 0.24.2
        e:
            5je68e9f1nji6coo8mryul80v027311r:
                args:
                    - --classifier_ckpt
                    - checkpoints/task1_best.pth
                    - --freeze_encoder
                    - --run_name
                    - strict_frozen
                codePath: train_segmentation.py
                codePathLocal: train_segmentation.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "869372051456"
                        used: "740991553536"
                email: ch22b007@smail.iitm.ac.in
                executable: /mnt/d_disk/ch22b007/da6401_assignment_2/da6401_2/bin/python
                git:
                    commit: bb25204278e06f00689c7e14c2f7a976b5523ede
                    remote: https://github.com/OjasPhadake/da6401_assignment_2.git
                gpu: NVIDIA RTX A6000
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-fc493a51-424d-467b-6be6-d84561ed87fe
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-c580d581-3f3b-5207-f1aa-1517e6b85c3c
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-e4183f3e-2434-20e9-c949-2ff9ef943220
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-de949f50-4e82-a9d1-2360-41cea646b452
                host: senaicluster
                memory:
                    total: "134889144320"
                os: Linux-5.15.0-125-generic-x86_64-with-glibc2.29
                program: train_segmentation.py
                python: CPython 3.8.10
                root: /mnt/d_disk/ch22b007/da6401_assignment_2
                startedAt: "2026-04-11T10:38:45.899181Z"
                writerId: 5je68e9f1nji6coo8mryul80v027311r
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
            "2":
                - 1
                - 80
            "3":
                - 1
                - 13
                - 16
            "4": 3.8.10
            "5": 0.24.2
            "12": 0.24.2
            "13": linux-x86_64
batch_size:
    value: 16
ckpt_dir:
    value: /mnt/d_disk/ch22b007/da6401_assignment_2/checkpoints
classifier_ckpt:
    value: checkpoints/task1_best.pth
data_root:
    value: /mnt/d_disk/ch22b007/da6401_assignment_2/data
dice_weight:
    value: 1
dropout_p:
    value: 0.5
epochs:
    value: 30
freeze_encoder:
    value: true
freeze_stages:
    value: null
image_size:
    value: 224
lr_backbone:
    value: 0.0001
lr_decoder:
    value: 0.001
no_wandb:
    value: false
num_workers:
    value: 4
resume:
    value: null
run_name:
    value: strict_frozen
seed:
    value: 42
val_split:
    value: 0.1
wandb_project:
    value: da6401_a2_task3
weight_decay:
    value: 0.0001
