_wandb:
    value:
        cli_version: 0.24.2
        e:
            pi8kszgkbbds8mdytfw1ukpfxrokqm4d:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "869372051456"
                        used: "740990500864"
                email: ch22b007@smail.iitm.ac.in
                executable: /mnt/d_disk/ch22b007/da6401_assignment_2/da6401_2/bin/python3
                git:
                    commit: 34aa1e41b31cfba8ba22a1af0a7044621c9991cb
                    remote: https://github.com/OjasPhadake/da6401_assignment_2.git
                gpu: NVIDIA RTX A6000
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-fc493a51-424d-467b-6be6-d84561ed87fe
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-c580d581-3f3b-5207-f1aa-1517e6b85c3c
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-e4183f3e-2434-20e9-c949-2ff9ef943220
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-de949f50-4e82-a9d1-2360-41cea646b452
                host: senaicluster
                memory:
                    total: "134889144320"
                os: Linux-5.15.0-125-generic-x86_64-with-glibc2.29
                program: train.py
                python: CPython 3.8.10
                root: /mnt/d_disk/ch22b007/da6401_assignment_2
                startedAt: "2026-04-11T09:33:22.746562Z"
                writerId: pi8kszgkbbds8mdytfw1ukpfxrokqm4d
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
                - 80
            "3":
                - 1
                - 2
                - 16
            "4": 3.8.10
            "5": 0.24.2
            "12": 0.24.2
            "13": linux-x86_64
batch_size:
    value: 32
ckpt_dir:
    value: /mnt/d_disk/ch22b007/da6401_assignment_2/checkpoints
data_root:
    value: /mnt/d_disk/ch22b007/da6401_assignment_2/data
dropout_p:
    value: 0.5
epochs:
    value: 30
image_size:
    value: 224
label_smoothing:
    value: 0.1
lr:
    value: 0.001
no_wandb:
    value: false
num_classes:
    value: 37
num_workers:
    value: 4
resume:
    value: null
run_name:
    value: null
seed:
    value: 42
val_split:
    value: 0.1
wandb_project:
    value: da6401_a2_task1
weight_decay:
    value: 0.0001
